## Imports and Data Loading

In [81]:
import pandas as pd
import numpy as np
# Linear regression
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [82]:
data_preprocessed = pd.read_csv('./data/1_Preprocessing/train.csv')
data_not_preprocessed = pd.read_csv('./data/0_Data_Split/train.csv')

#### Multiple Subdatasets

In [83]:
# NaN values
print(data_preprocessed.isnull().sum())
data_preprocessed.head()

model_year        0
milage            0
accident          0
clean_title       0
price             0
horsepower        0
turbo             0
is_luxury         0
is_upper_class    0
dtype: int64

,model_year,milage,accident,clean_title,price,horsepower,turbo,is_luxury,is_upper_class
0,2000,194277.0,1,1,2300,222.000000,0,0,0
1,2015,13300.0,0,1,62500,449.000000,0,0,0
2,2020,30426.0,1,0,29645,256.333333,0,0,0
3,2020,67072.0,0,1,38500,375.000000,0,0,0
4,2016,99000.0,1,1,5000,172.000000,0,0,0

In [84]:
# Without preprocessing
print(data_not_preprocessed.isnull().sum())
data_not_preprocessed.head()

brand             0
model             0
model_year        0
milage            0
fuel_type       135
engine            0
transmission      0
ext_col           0
int_col           0
accident         87
clean_title     472
price             0
dtype: int64

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Nissan,Maxima GLE,2000,"194,277 mi.",Gasoline,222.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Beige,At least 1 accident or damage reported,Yes,2300
1,Mercedes-Benz,S-Class S 550 4MATIC,2015,"13,300 mi.",Gasoline,449.0HP 4.7L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,62500
2,GMC,Acadia SLE,2020,"30,426 mi.",Gasoline,2.5L I4 16V GDI DOHC,9-Speed Automatic,Ebony Twilight Metallic,Jet Black,NaN,NaN,29645
3,Ford,Expedition Max XLT,2020,"67,072 mi.",Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Purple,Black,None reported,Yes,38500
4,Jeep,Compass Sport,2016,"99,000 mi.",Gasoline,172.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Gray,At least 1 accident or damage reported,Yes,5000

In [85]:
# Complete case
data_not_preprocessed_cc = data_not_preprocessed.dropna()
print("The new shape of the data is: ", data_not_preprocessed_cc.shape)
data_not_preprocessed_cc.isnull().sum()

The new shape of the data is:  (2622, 12)

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [86]:
# How often is "" or "-" in the data?
print(data_not_preprocessed_cc[data_not_preprocessed_cc == ""].count())
print(data_not_preprocessed_cc[data_not_preprocessed_cc == "-"].count())
print(data_not_preprocessed_cc[data_not_preprocessed_cc == "not supported"].count())

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64
brand           0
model           0
model_year      0
milage          0
fuel_type       1
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [87]:
data_not_preprocessed_cc.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Nissan,Maxima GLE,2000,"194,277 mi.",Gasoline,222.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Beige,At least 1 accident or damage reported,Yes,2300
1,Mercedes-Benz,S-Class S 550 4MATIC,2015,"13,300 mi.",Gasoline,449.0HP 4.7L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,62500
3,Ford,Expedition Max XLT,2020,"67,072 mi.",Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Purple,Black,None reported,Yes,38500
4,Jeep,Compass Sport,2016,"99,000 mi.",Gasoline,172.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Gray,At least 1 accident or damage reported,Yes,5000
7,Toyota,4Runner Limited,2014,"146,700 mi.",Gasoline,270.0HP 4.0L V6 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Black,At least 1 accident or damage reported,Yes,24999

In [88]:
# Most common ext_col and int_col
print(data_not_preprocessed_cc['ext_col'].value_counts())
print(data_not_preprocessed_cc['int_col'].value_counts())

ext_col
Black                      633
White                      585
Gray                       360
Silver                     271
Blue                       247
                          ...
Glacier Silver Metallic      1
Carrara White Metallic       1
Blue Reflex Mica             1
Shadow Gray Metallic         1
Rich Garnet Metallic         1
Name: count, Length: 98, dtype: int64
int_col
Black            1347
Beige             397
Gray              349
Brown             133
–                  84
                 ...
Light Slate         1
Medium Pewter       1
Graphite            1
White / Brown       1
Chestnut            1
Name: count, Length: 63, dtype: int64

In [89]:
len(data_not_preprocessed_cc["brand"].unique())

52

In [90]:
# Little Preprocessing of original data

# Tranformation of milage (String to int)
data_not_preprocessed['milage'] = data_not_preprocessed['milage'].str.replace(' mi.', '')
data_not_preprocessed['milage'] = data_not_preprocessed['milage'].str.replace(',', '')

# Dummy variables

def transform_string(series):
    '''
    Function to transform a series of strings into column names
    ----------------
    Parameters:
        series(pd.Series): Series of strings to transform
    ----------------
    Returns:
        pd.DataFrame: DataFrame with dummy variables
    '''
    series = series.str.replace(' ', '_')
    series = series.str.replace('-', '_')
    series = series.str.replace('/', '_')
    print(series)
    return pd.get_dummies(series)

## fuel_type should be a dummy variable
dummy_placeholder = pd.get_dummies(data_not_preprocessed_cc['fuel_type'])
data_not_preprocessed_cc = pd.concat([data_not_preprocessed_cc, dummy_placeholder], axis=1)
data_not_preprocessed_cc.drop('fuel_type', axis=1, inplace=True)
data_not_preprocessed_cc.drop(['not supported', '–'], axis=1, inplace=True)

# Dummy if ext_col is Black, White, Grey, Silver
data_not_preprocessed_cc['is_black'] = data_not_preprocessed_cc['ext_col'].apply(lambda x: 1 if x == 'Black' else 0)
data_not_preprocessed_cc['is_white'] = data_not_preprocessed_cc['ext_col'].apply(lambda x: 1 if x == 'White' else 0)
data_not_preprocessed_cc['is_grey'] = data_not_preprocessed_cc['ext_col'].apply(lambda x: 1 if x == 'Grey' else 0)

# Dummy of brand
dummy_placeholder = pd.get_dummies(data_not_preprocessed_cc['brand'])
data_not_preprocessed_cc = pd.concat([data_not_preprocessed_cc, dummy_placeholder], axis=1)
data_not_preprocessed_cc.drop('brand', axis=1, inplace=True)

# Convert True and False to 1 and 0 for every column
for column in data_not_preprocessed_cc.columns:
    if data_not_preprocessed_cc[column].dtype == 'bool':
        data_not_preprocessed_cc[column] = data_not_preprocessed_cc[column].apply(lambda x: 1 if x == True else 0)

# Convert clean_title to 1 and 0
data_not_preprocessed_cc['clean_title'] = data_not_preprocessed_cc['clean_title'].apply(lambda x: 1 if x == 'Yes' else 0)

# Drop transmission, engine, accident, model
data_not_preprocessed_cc.drop(['transmission', 'engine', 'accident', 'model', 'ext_col', 'int_col'], axis=1, inplace=True)

# Modelyear in age
data_not_preprocessed_cc['age'] = 2024 - data_not_preprocessed_cc['model_year']

# Drop model_year
data_not_preprocessed_cc.drop('model_year', axis=1, inplace=True)

# convert milage to int
data_not_preprocessed_cc['milage'] = data_not_preprocessed_cc['milage'].str.replace(' mi.', '')
data_not_preprocessed_cc['milage'] = data_not_preprocessed_cc['milage'].str.replace(',', '')
data_not_preprocessed_cc['milage'] = data_not_preprocessed_cc['milage'].astype(int)

data_not_preprocessed_cc.head()

,milage,clean_title,price,Diesel,E85 Flex Fuel,Gasoline,Hybrid,Plug-In Hybrid,is_black,is_white,...,Saab,Saturn,Scion,Subaru,Suzuki,Toyota,Volkswagen,Volvo,smart,age
0,194277,1,2300,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,24
1,13300,1,62500,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,9
3,67072,1,38500,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,99000,1,5000,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,8
7,146700,1,24999,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,10

### Statsmodels of complete case

In [111]:
data = data_not_preprocessed_cc.copy()

# Drop all rows with price over 120000
data = data[data['price'] < 100000]

# Drop all constant columns
data = data.loc[:, (data != data.iloc[0]).any()]

# Drop this columns, because of leave one out: Gasoline
data.drop(['Gasoline'], axis=1, inplace=True)
y = data['price']
X = data.drop('price', axis=1)

model = sm.OLS(y, X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.601
Model:                            OLS   Adj. R-squared:                  0.592
Method:                 Least Squares   F-statistic:                     66.83
Date:                Sat, 30 Nov 2024   Prob (F-statistic):               0.00
Time:                        19:51:38   Log-Likelihood:                -27209.
No. Observations:                2495   AIC:                         5.453e+04
Df Residuals:                    2439   BIC:                         5.486e+04
Df Model:                          55
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
milage            -0.1648      0.007    -24.985      0.000      -0.178      -0.152
Diesel          1.565e+04   1580.940      9.896      0.000    1.25e+04    1.87e+04
E85 Flex Fuel  -3134.1690   1446.859     -2.166      0.030   -5971.368    -296.970
Hybrid          5274.8001   1367.645      3.857      0.000    2592.933    7956.667
Plug-In Hybrid  2507.7876   2613.709      0.959      0.337   -2617.531    7633.107
is_black          92.1594    670.121      0.138      0.891   -1221.906    1406.225
is_white        -659.6806    681.424     -0.968      0.333   -1995.910     676.549
Acura           5.204e+04   2254.491     23.081      0.000    4.76e+04    5.65e+04
Alfa            4.702e+04   4232.956     11.108      0.000    3.87e+04    5.53e+04
Aston           7.376e+04   7737.470      9.533      0.000    5.86e+04    8.89e+04
Audi            5.203e+04   1351.248     38.504      0.000    4.94e+04    5.47e+04
BMW             5.733e+04   1024.744     55.944      0.000    5.53e+04    5.93e+04
Bentley         8.283e+04   4124.957     20.080      0.000    7.47e+04    9.09e+04
Buick           4.559e+04   3034.580     15.023      0.000    3.96e+04    5.15e+04
Cadillac        5.735e+04   1706.680     33.605      0.000     5.4e+04    6.07e+04
Chevrolet       6.041e+04   1083.030     55.775      0.000    5.83e+04    6.25e+04
Chrysler        4.223e+04   2986.112     14.142      0.000    3.64e+04    4.81e+04
Dodge           5.569e+04   1790.531     31.100      0.000    5.22e+04    5.92e+04
FIAT            3.412e+04   7709.165      4.426      0.000     1.9e+04    4.92e+04
Ford             5.48e+04    987.026     55.521      0.000    5.29e+04    5.67e+04
GMC             5.691e+04   1722.789     33.035      0.000    5.35e+04    6.03e+04
Genesis         4.975e+04   3576.013     13.912      0.000    4.27e+04    5.68e+04
Honda           5.269e+04   2204.786     23.899      0.000    4.84e+04     5.7e+04
Hummer          6.509e+04   3812.717     17.071      0.000    5.76e+04    7.26e+04
Hyundai         3.997e+04   2019.318     19.794      0.000     3.6e+04    4.39e+04
INFINITI         4.72e+04   2092.027     22.560      0.000    4.31e+04    5.13e+04
Jaguar          5.173e+04   2445.867     21.148      0.000    4.69e+04    5.65e+04
Jeep            5.258e+04   1492.724     35.225      0.000    4.97e+04    5.55e+04
Kia             3.866e+04   2268.707     17.039      0.000    3.42e+04    4.31e+04
Land            6.045e+04   1699.097     35.576      0.000    5.71e+04    6.38e+04
Lexus           5.729e+04   1466.528     39.063      0.000    5.44e+04    6.02e+04
Lincoln         5.058e+04   2330.482     21.705      0.000     4.6e+04    5.52e+04
Lotus           7.506e+04   7730.762      9.709      0.000    5.99e+04    9.02e+04
MINI            3.963e+04   2723.479     14.552      0.000    3.43e+04     4.5e+04
Maserati        5.846e+04   2828.657     20.666      0.000    5.29e+04     6.4e+04
Maybach         9.421e+04   1.34e+04      7.045      0.000     6.8e+04     1.2e+05
Mazda           4.162e+04   2019.764     20.606      0.000    3.77e+04    4.56e+04
Mercedes-Benz   5.773e+04   1128.956     51.138      0.000    5.55e+04    5.99e+04
Mercury         5.808e+04   7781.874      7.464      0.000    4.28e+04    7.33e+04
Mitsubishi      5.134e+04   3313.466     15.494      0.000    4.48e+04    5.78e+04
Nissan          5.273e+04   1659.643     31.770      0.000    4.95e+04     5.6e+04
Plymouth        6.013e+04   1.34e+04      4.491      0.000    3.39e+04    8.64e+04
Pontiac         5.208e+04   3964.260     13.138      0.000    4.43e+04    5.99e+04
Porsche         7.134e+04   1468.337     48.588      0.000    6.85e+04    7.42e+04
RAM             5.436e+04   1844.990     29.462      0.000    5.07e+04     5.8e+04
Rolls-Royce      1.04e+05   9454.204     11.004      0.000    8.55e+04    1.23e+05
Saab            4.776e+04   9473.357      5.041      0.000    2.92e+04    6.63e+04
Saturn           4.42e+04   6723.065      6.574      0.000     3.1e+04    5.74e+04
Scion           4.304e+04   6701.670      6.422      0.000    2.99e+04    5.62e+04
Subaru          4.493e+04   1982.864     22.661      0.000     4.1e+04    4.88e+04
Suzuki          3.674e+04   1.33e+04      2.754      0.006    1.06e+04    6.29e+04
Toyota          5.527e+04   1323.093     41.776      0.000    5.27e+04    5.79e+04
Volkswagen      4.335e+04   2168.238     19.994      0.000    3.91e+04    4.76e+04
Volvo           5.005e+04   2626.040     19.060      0.000    4.49e+04    5.52e+04
smart            3.46e+04   1.34e+04      2.591      0.010    8414.664    6.08e+04
age            -1215.5856     57.902    -20.994      0.000   -1329.129   -1102.043
==============================================================================
Omnibus:                      486.535   Durbin-Watson:                   1.977
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1074.805
Skew:                           1.109   Prob(JB):                    4.06e-234
Kurtosis:                       5.329   Cond. No.                     4.65e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.65e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [112]:
# All significant variables
summary = model.summary()
summary = summary.tables[1]
summary = pd.DataFrame(summary.data)
summary.columns = summary.iloc[0]
summary = summary[1:]
summary.sort_values('P>|t|', inplace=True)
# coefs should be converted to float without e-notation
summary['coef'] = summary['coef'].astype(float).apply(lambda x: '{:.2f}'.format(x))

pd.set_option('display.max_rows', None)
summary.head(100)

,,coef,std err,t,P>|t|,[0.025,0.975]
1,milage,-0.16,0.007,-24.985,0.000,-0.178,-0.152
31,Lexus,57290.00,1466.528,39.063,0.000,5.44e+04,6.02e+04
32,Lincoln,50580.00,2330.482,21.705,0.000,4.6e+04,5.52e+04
33,Lotus,75060.00,7730.762,9.709,0.000,5.99e+04,9.02e+04
34,MINI,39630.00,2723.479,14.552,0.000,3.43e+04,4.5e+04
35,Maserati,58460.00,2828.657,20.666,0.000,5.29e+04,6.4e+04
36,Maybach,94210.00,1.34e+04,7.045,0.000,6.8e+04,1.2e+05
37,Mazda,41620.00,2019.764,20.606,0.000,3.77e+04,4.56e+04
38,Mercedes-Benz,57730.00,1128.956,51.138,0.000,5.55e+04,5.99e+04
39,Mercury,58080.00,7781.874,7.464,0.000,4.28e+04,7.33e+04
40,Mitsubishi,51340.00,3313.466,15.494,0.000,4.48e+04,5.78e+04
41,Nissan,52730.00,1659.643,31.770,0.000,4.95e+04,5.6e+04
42,Plymouth,60130.00,1.34e+04,4.491,0.000,3.39e+04,8.64e+04
43,Pontiac,52080.00,3964.260,13.138,0.000,4.43e+04,5.99e+04
44,Porsche,71340.00,1468.337,48.588,0.000,6.85e+04,7.42e+04
45,RAM,54360.00,1844.990,29.462,0.000,5.07e+04,5.8e+04
46,Rolls-Royce,104000.00,9454.204,11.004,0.000,8.55e+04,1.23e+05
47,Saab,47760.00,9473.357,5.041,0.000,2.92e+04,6.63e+04
48,Saturn,44200.00,6723.065,6.574,0.000,3.1e+04,5.74e+04
49,Scion,43040.00,6701.670,6.422,0.000,2.99e+04,5.62e+04
50,Subaru,44930.00,1982.864,22.661,0.000,4.1e+04,4.88e+04
52,Toyota,55270.00,1323.093,41.776,0.000,5.27e+04,5.79e+04
53,Volkswagen,43350.00,2168.238,19.994,0.000,3.91e+04,4.76e+04
54,Volvo,50050.00,2626.040,19.060,0.000,4.49e+04,5.52e+04
30,Land,60450.00,1699.097,35.576,0.000,5.71e+04,6.38e+04
29,Kia,38660.00,2268.707,17.039,0.000,3.42e+04,4.31e+04
28,Jeep,52580.00,1492.724,35.225,0.000,4.97e+04,5.55e+04
13,Bentley,82830.00,4124.957,20.080,0.000,7.47e+04,9.09e+04
2,Diesel,15650.00,1580.940,9.896,0.000,1.25e+04,1.87e+04
4,Hybrid,5274.80,1367.645,3.857,0.000,2592.933,7956.667
8,Acura,52040.00,2254.491,23.081,0.000,4.76e+04,5.65e+04
9,Alfa,47020.00,4232.956,11.108,0.000,3.87e+04,5.53e+04
10,Aston,73760.00,7737.470,9.533,0.000,5.86e+04,8.89e+04
11,Audi,52030.00,1351.248,38.504,0.000,4.94e+04,5.47e+04
12,BMW,57330.00,1024.744,55.944,0.000,5.53e+04,5.93e+04
27,Jaguar,51730.00,2445.867,21.148,0.000,4.69e+04,5.65e+04
14,Buick,45590.00,3034.580,15.023,0.000,3.96e+04,5.15e+04
15,Cadillac,57350.00,1706.680,33.605,0.000,5.4e+04,6.07e+04
56,age,-1215.59,57.902,-20.994,0.000,-1329.129,-1102.043
17,Chrysler,42230.00,2986.112,14.142,0.000,3.64e+04,4.81e+04
18,Dodge,55690.00,1790.531,31.100,0.000,5.22e+04,5.92e+04
19,FIAT,34120.00,7709.165,4.426,0.000,1.9e+04,4.92e+04
20,Ford,54800.00,987.026,55.521,0.000,5.29e+04,5.67e+04
21,GMC,56910.00,1722.789,33.035,0.000,5.35e+04,6.03e+04
22,Genesis,49750.00,3576.013,13.912,0.000,4.27e+04,5.68e+04
23,Honda,52690.00,2204.786,23.899,0.000,4.84e+04,5.7e+04
24,Hummer,65090.00,3812.717,17.071,0.000,5.76e+04,7.26e+04
16,Chevrolet,60410.00,1083.030,55.775,0.000,5.83e+04,6.25e+04
26,INFINITI,47200.00,2092.027,22.560,0.000,4.31e+04,5.13e+04
25,Hyundai,39970.00,2019.318,19.794,0.000,3.6e+04,4.39e+04
51,Suzuki,36740.00,1.33e+04,2.754,0.006,1.06e+04,6.29e+04
55,smart,34600.00,1.34e+04,2.591,0.010,8414.664,6.08e+04
3,E85 Flex Fuel,-3134.17,1446.859,-2.166,0.030,-5971.368,-296.970
7,is_white,-659.68,681.424,-0.968,0.333,-1995.910,676.549
5,Plug-In Hybrid,2507.79,2613.709,0.959,0.337,-2617.531,7633.107
6,is_black,92.16,670.121,0.138,0.891,-1221.906,1406.225

#### Statsmodels of preprocessed data

In [118]:
data = data_preprocessed.copy()

# Drop all rows with price over 120000
data = data[data['price'] < 100000]

# Drop all constant columns
data = data.loc[:, (data != data.iloc[0]).any()]

# Modelyear in age
data['age'] = 2024 - data['model_year']
data.drop('model_year', axis=1, inplace=True)

y = data['price']
X = data.drop('price', axis=1)

model = sm.OLS(y, X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.905
Model:                            OLS   Adj. R-squared (uncentered):              0.904
Method:                 Least Squares   F-statistic:                              3573.
Date:                Sat, 30 Nov 2024   Prob (F-statistic):                        0.00
Time:                        19:58:39   Log-Likelihood:                         -32786.
No. Observations:                3024   AIC:                                  6.559e+04
Df Residuals:                    3016   BIC:                                  6.564e+04
Df Model:                           8
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
milage            -0.1201      0.006    -21.324      0.000      -0.131      -0.109
accident       -1058.9007    514.427     -2.058      0.040   -2067.563     -50.238
clean_title     6818.1986    620.799     10.983      0.000    5600.966    8035.431
horsepower       123.6834      1.466     84.365      0.000     120.809     126.558
turbo           6318.0933    953.359      6.627      0.000    4448.793    8187.394
is_luxury       3730.5404   2973.787      1.254      0.210   -2100.315    9561.396
is_upper_class  3761.1374    747.131      5.034      0.000    2296.200    5226.075
age             -672.6747     47.114    -14.278      0.000    -765.053    -580.296
==============================================================================
Omnibus:                      258.670   Durbin-Watson:                   1.982
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              437.058
Skew:                           0.620   Prob(JB):                     1.24e-95
Kurtosis:                       4.390   Cond. No.                     1.13e+06
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.13e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""